In [57]:
# 2. Czyszczenie i przygotowanie danych

In [58]:
import pandas as pd

df = pd.read_csv('ogloszenia_trojmiasto.csv')
df.head()

,id,url,date_posted,photos,locality,street,property_type,rooms,area_m2,owner_direct,price_total_zl,price_per_m2_zl,city
0,o,https://adresowo.pl/o/mieszkanie-gdansk-jasien...,3 dni temu,12.0,Gdańsk Jasień,ul. Kazimierza Leskiego,Apartment,2.0,41.0,Bez pośredników,639000,15582.0,Gdańsk
1,o,https://adresowo.pl/o/mieszkanie-gdynia-srodmi...,dzisiajnowe,16.0,Gdynia Śródmieście,ul. A. Hryniewickiego,Apartment,3.0,80.0,Bez pośredników,2800000,35000.0,Gdynia
2,o,https://adresowo.pl/o/mieszkanie-gdansk-wrzesz...,dzisiajnowe,7.0,Gdańsk Wrzeszcz,NaN,Apartment,1.0,27.0,Bez pośredników,465000,17222.0,Gdańsk
3,o,https://adresowo.pl/o/mieszkanie-gdansk-orunia...,NaN,7.0,Gdańsk Orunia Górna,ul. Kazimierza Wielkiego,Apartment,2.0,40.0,Bez pośredników,zapytaj o cenę,NaN,Gdańsk
4,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,NaN,NaN,Pośrednik,NaN,NaN,NaN

In [59]:
df.shape

(1145, 13)

In [60]:
df = df.drop_duplicates()
df = df.dropna(subset=['price_total_zl', 'area_m2'])
df = df.drop(columns=['id'])
df.head()

,url,date_posted,photos,locality,street,property_type,rooms,area_m2,owner_direct,price_total_zl,price_per_m2_zl,city
0,https://adresowo.pl/o/mieszkanie-gdansk-jasien...,3 dni temu,12.0,Gdańsk Jasień,ul. Kazimierza Leskiego,Apartment,2.0,41.0,Bez pośredników,639000,15582.0,Gdańsk
1,https://adresowo.pl/o/mieszkanie-gdynia-srodmi...,dzisiajnowe,16.0,Gdynia Śródmieście,ul. A. Hryniewickiego,Apartment,3.0,80.0,Bez pośredników,2800000,35000.0,Gdynia
2,https://adresowo.pl/o/mieszkanie-gdansk-wrzesz...,dzisiajnowe,7.0,Gdańsk Wrzeszcz,NaN,Apartment,1.0,27.0,Bez pośredników,465000,17222.0,Gdańsk
3,https://adresowo.pl/o/mieszkanie-gdansk-orunia...,NaN,7.0,Gdańsk Orunia Górna,ul. Kazimierza Wielkiego,Apartment,2.0,40.0,Bez pośredników,zapytaj o cenę,NaN,Gdańsk
6,https://adresowo.pl/o/mieszkanie-gdansk-morena...,dzisiajnowe,10.0,Gdańsk Morena,ul. Warneńska,Apartment,2.0,47.0,Oferta biura nieruchomości,569000,12106.0,Gdańsk

In [61]:
print(df.shape)

(1007, 12)

In [62]:
df = df[df['price_total_zl']!='zapytaj o cenę']
df['price_total_zl_cleaned'] = df['price_total_zl'].astype(float)

In [63]:
print(df.shape)

(992, 13)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 992 entries, 0 to 1144
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   url                     992 non-null    object
 1   date_posted             992 non-null    object
 2   photos                  992 non-null    float64
 3   locality                992 non-null    object
 4   street                  915 non-null    object
 5   property_type           992 non-null    object
 6   rooms                   992 non-null    float64
 7   area_m2                 992 non-null    float64
 8   owner_direct            992 non-null    object
 9   price_total_zl          992 non-null    object
 10  price_per_m2_zl         992 non-null    float64
 11  city                    992 non-null    object
 12  price_total_zl_cleaned  992 non-null    float64
dtypes: float64(5), object(8)
memory usage: 108.5+ KB

In [65]:
# Tworzę zmienną z 'cleaned' w nazwie, bo potem mi się przyda zmienna z tą nazwą
df['price_per_m2_zl_cleaned'] = df['price_per_m2_zl'].astype(float)

In [66]:
# Dodaję nową zmienną: area_per_room
df['area_per_room'] = df['area_m2'] / df['rooms'].astype(float).round(1)
df.head()

,url,date_posted,photos,locality,street,property_type,rooms,area_m2,owner_direct,price_total_zl,price_per_m2_zl,city,price_total_zl_cleaned,price_per_m2_zl_cleaned,area_per_room
0,https://adresowo.pl/o/mieszkanie-gdansk-jasien...,3 dni temu,12.0,Gdańsk Jasień,ul. Kazimierza Leskiego,Apartment,2.0,41.0,Bez pośredników,639000,15582.0,Gdańsk,639000.0,15582.0,20.500000
1,https://adresowo.pl/o/mieszkanie-gdynia-srodmi...,dzisiajnowe,16.0,Gdynia Śródmieście,ul. A. Hryniewickiego,Apartment,3.0,80.0,Bez pośredników,2800000,35000.0,Gdynia,2800000.0,35000.0,26.666667
2,https://adresowo.pl/o/mieszkanie-gdansk-wrzesz...,dzisiajnowe,7.0,Gdańsk Wrzeszcz,NaN,Apartment,1.0,27.0,Bez pośredników,465000,17222.0,Gdańsk,465000.0,17222.0,27.000000
6,https://adresowo.pl/o/mieszkanie-gdansk-morena...,dzisiajnowe,10.0,Gdańsk Morena,ul. Warneńska,Apartment,2.0,47.0,Oferta biura nieruchomości,569000,12106.0,Gdańsk,569000.0,12106.0,23.500000
7,https://adresowo.pl/o/mieszkanie-gdansk-ul-pow...,dzisiajnowe,17.0,Gdańsk,ul. Powstania Listopadowego,Apartment,2.0,47.0,Oferta biura nieruchomości,550000,11677.0,Gdańsk,550000.0,11677.0,23.500000

In [67]:
# Sprawdzam, czy zostały jakieś NaNy
df.isna().sum()

url                         0
date_posted                 0
photos                      0
locality                    0
street                     77
property_type               0
rooms                       0
area_m2                     0
owner_direct                0
price_total_zl              0
price_per_m2_zl             0
city                        0
price_total_zl_cleaned      0
price_per_m2_zl_cleaned     0
area_per_room               0
dtype: int64

In [68]:
# Zapisuję wyczyszczony plik
df.to_csv('cleaned_trojmiasto.csv', index=False)

In [69]:
# Polecenie: Przefiltruj dane dla Gdańska, Gdyni i Sopotu.
df_gdynia = df[df['city'] == 'Gdynia']
df_gdansk = df[df['city'] == 'Gdańsk']
df_sopot = df[df['city'] == 'Sopot']
print('Gdynia:', df_gdynia.shape, 'Gdańsk:', df_gdansk.shape, 'Sopot:', df_sopot.shape, 'Total:', df.shape)

Gdynia: (269, 15) Gdańsk: (664, 15) Sopot: (59, 15) Total: (992, 15)